/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import BaseDeDatos.Bd;
import Pojos.ConfiguracionPrestamos;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author berli
 */
public class ModuloConfig extends javax.swing.JDialog {

    private DefaultTableModel modelo = new DefaultTableModel();
    private List<JTextField> listaa;
    private ConfiguracionPrestamos configSeleccionada;
    private boolean voyAGuardarUnaConfiguracionu = true;
    private boolean habilitarListenerDeFocus = true;

    /**
     * Creates new form ModuloConfig
     */
    public ModuloConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        listaa = ListaDeTxt();
        formatoTabla();
        metodosGenerales.camposDeTextoMayuscula(listaa);
        metodosGenerales.limitarCaracteresParaConjunto(listaa, 50);
        metodosGenerales.unCampoDeTextoMayuscula(txtBuscador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNumeroCuotas = new javax.swing.JTextField();
        comboModalida = new javax.swing.JComboBox<>();
        txtBeneficio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreConfiguracion = new javax.swing.JTextField();
        txtNombreCompania = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNumeroCuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCuotasKeyTyped(evt);
            }
        });

        comboModalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanal", "Diario" }));

        txtBeneficio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBeneficioKeyTyped(evt);
            }
        });

        jLabel6.setText("Codigo");

        jLabel1.setText("Nombre de Conguracion");

        txtCodigo.setText("Cod");

        jLabel2.setText("Nombre de Compania");

        jLabel3.setText("Numero de Cuotas");

        jLabel4.setText("Modalidad");

        jLabel5.setText("% Beneficio");

        txtNombreConfiguracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreConfiguracionKeyTyped(evt);
            }
        });

        txtNombreCompania.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCompaniaKeyTyped(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevo);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(txtNombreConfiguracion)
                    .addComponent(txtNombreCompania)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNumeroCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 136, Short.MAX_VALUE))
                            .addComponent(comboModalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(txtNombreCompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboModalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtCodigo.setFocusable(false);

        jTabbedPane1.addTab("Configuracion", jPanel2);

        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        tabla.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tabla.setForeground(new java.awt.Color(51, 51, 51));
        tabla.setModel(modelo);
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setRowHeight(20);
        tabla.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(txtBuscador))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroCuotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCuotasKeyTyped
        metodosGenerales.formatoNumericoTextField(evt, txtNumeroCuotas, 2);
    }//GEN-LAST:event_txtNumeroCuotasKeyTyped

    private void txtBeneficioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeneficioKeyTyped
        metodosGenerales.formatoNumericoTextField(evt, txtBeneficio, 2);
    }//GEN-LAST:event_txtBeneficioKeyTyped

    private void txtNombreConfiguracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreConfiguracionKeyTyped
        metodosGenerales.limitarCaracteres(evt, txtNombreConfiguracion, 35);
    }//GEN-LAST:event_txtNombreConfiguracionKeyTyped

    private void txtNombreCompaniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCompaniaKeyTyped
        metodosGenerales.limitarCaracteres(evt, txtNombreCompania, 35);
    }//GEN-LAST:event_txtNombreCompaniaKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        funcionalidadDeBotonGuardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        funcioalidadBotonEditar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        funcionalidadDeBotonCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        funcionalidadDeBotonNuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        if (evt.getClickCount() == 2) {
            rellenarCampos();
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && tabla.getSelectedRow()> -1) {
            rellenarCampos();
        }
    }//GEN-LAST:event_tablaKeyPressed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscarPorCriterioConf(txtBuscador.getText());
    }//GEN-LAST:event_txtBuscadorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModuloConfig dialog = new ModuloConfig(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> comboModalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBeneficio;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombreCompania;
    private javax.swing.JTextField txtNombreConfiguracion;
    private javax.swing.JTextField txtNumeroCuotas;
    // End of variables declaration//GEN-END:variables

    private List<JTextField> ListaDeTxt() {
        return Arrays.asList(new JTextField[]{txtNombreConfiguracion, txtNombreCompania, txtNumeroCuotas, txtBeneficio});
    }

    private void habilitarCampos(boolean valor) {
        listaa.forEach(txt -> {
            txt.setFocusable(valor);
        });
        comboModalida.setEnabled(valor);
        btnEditar.setEnabled(!valor);
        btnGuardar.setEnabled(valor);
    }

    private void formatoTabla() {
        tabla.setDefaultEditor(Object.class, null);
        String[] titulos = {"Id", "Configuracion", "Empresa", "Cuotas", "Modalidad", "Beneficio"};
        int[] tamanos = {50, 150, 150, 50, 50, 50};
        metodosGenerales.FormatoTablas(tabla, modelo, titulos, tamanos);
        titulos = null;
        tamanos = null;
    }

    private void funcionalidadDeBotonNuevo() {
        metodosGenerales.borrarTxt(listaa);
        comboModalida.setSelectedIndex(0);
        habilitarCampos(true);
        voyAGuardarUnaConfiguracionu = true;
    }

    private void funcionalidadDeBotonGuardar() {

        boolean hayCampoVacio = metodosGenerales.hayUnCampoVacio(listaa);

        if (voyAGuardarUnaConfiguracionu) {

            if (!hayCampoVacio) {

                int indice = 1;
                String nombreConfiguracion = txtNombreConfiguracion.getText();
                String nombreCompania = txtNombreCompania.getText();
                int numeroDeCuotas = Integer.parseInt(txtNumeroCuotas.getText());
                String modalidad = comboModalida.getSelectedItem().toString();
                int porCientoBeneficio = Integer.parseInt(txtBeneficio.getText());

                Bd.insertarConfiguracionPrestamos(new ConfiguracionPrestamos(indice, nombreConfiguracion, nombreCompania, numeroDeCuotas, modalidad, porCientoBeneficio));

                metodosGenerales.borrarTxt(listaa);
                comboModalida.setSelectedIndex(0);
                txtNombreConfiguracion.grabFocus();
                btnEditar.setEnabled(false);
            }

        } else {

            if (!hayCampoVacio) {

                int id = configSeleccionada.getIdConf();
                String nombreConfiguracion = txtNombreConfiguracion.getText();
                String nombreCompania = txtNombreCompania.getText();
                int cuota = Integer.parseInt(txtNumeroCuotas.getText());
                String modalidad = comboModalida.getSelectedItem().toString();
                int beneficio = Integer.parseInt(txtBeneficio.getText());

                System.out.println(id);

                Bd.editarConfiguracionPrestamos(new ConfiguracionPrestamos(id, nombreConfiguracion, nombreCompania, cuota, modalidad, beneficio));

                metodosGenerales.borrarTxt(listaa);
                comboModalida.setSelectedIndex(0);
                txtNombreConfiguracion.grabFocus();
                voyAGuardarUnaConfiguracionu = true;
            }
        }

        if (habilitarListenerDeFocus == true) {
            metodosGenerales.focusPerdidoTxt(listaa);
            habilitarListenerDeFocus = false;
        }
    }

    private void funcioalidadBotonEditar() {
        voyAGuardarUnaConfiguracionu = false;
        habilitarCampos(true);
    }

    private void funcionalidadDeBotonCancelar() {
        if (metodosGenerales.hayAlmenosUnCampoLleno(listaa)) {
            metodosGenerales.borrarTxt(listaa);
            habilitarCampos(true);
            comboModalida.setSelectedIndex(0);
            voyAGuardarUnaConfiguracionu = true;
        } else {
            dispose();
        }
    }

    private void buscarPorCriterioConf(String criterio) {
        metodosGenerales.LimpiarTabla(modelo);
        List<ConfiguracionPrestamos> lista = Bd.buscarConfiguracionPrestamos(criterio);
        modelo.setRowCount(lista.size());
        ConfiguracionPrestamos c;

        for (int i = 0; i < lista.size(); i++) {
            c = lista.get(i);
            modelo.setValueAt(c.getIdConf(), i, 0);
            modelo.setValueAt(c, i, 1);
            modelo.setValueAt(c.getNombreCompania(), i, 2);
            modelo.setValueAt(c.getNumeroDeCuotas(), i, 3);
            modelo.setValueAt(c.getModalida(), i, 4);
            modelo.setValueAt(c.getPorCientoBeneficio(), i, 5);
        }
        lista = null;
    }

    private void rellenarCampos() {

        int filaSeleccionada = tabla.getSelectedRow();
        configSeleccionada = (ConfiguracionPrestamos) tabla.getValueAt(filaSeleccionada, 1);

        txtCodigo.setText(configSeleccionada.getIdConf()+"");
        txtNombreConfiguracion.setText(configSeleccionada.getNombreConfiguracion());
        txtNombreCompania.setText(configSeleccionada.getNombreCompania());
        comboModalida.setSelectedItem(configSeleccionada.getModalida());
        txtNumeroCuotas.setText(configSeleccionada.getNumeroDeCuotas()+"");
        txtBeneficio.setText(configSeleccionada.getPorCientoBeneficio()+"");

        metodosGenerales.LimpiarTabla(modelo);//anadido despues
        habilitarCampos(false);
        jTabbedPane1.setSelectedIndex(0);
    }

}
