package Gui;

import Gui.*;
import BaseDeDatos.Bd;
import Pojos.Cliente;
import Pojos.Cobrador;
import Pojos.ConfiguracionPrestamos;
import Pojos.Prestamo;
import Pojos.Recibo;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author berli
 *
 */
public class ModuloPrestamos extends javax.swing.JDialog {

    private DefaultTableModel modeloPrestamos = new DefaultTableModel();
    private DefaultTableModel modeloClientes = new DefaultTableModel();
    private DefaultTableModel modeloCuotas = new DefaultTableModel();
    private DefaultTableModel modeloPrestamosEliminados = new DefaultTableModel();

    private List<JTextField> lista;

    private Cobrador cobradorSeleccionado;
    private Cliente clienteSeleccionado;
    private ConfiguracionPrestamos conf;

    private boolean habilitarListenerDeFocus = true;
    int numeroDeUltimaSemanaQueSeCobro;

    public ModuloPrestamos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        formatoTabla();
        eventoAlSeleccionarUnEmpleado();
        lista = ListaDeTxt();
        jTabbedPane1.remove(3);
        jTabbedPane1.remove(2);
        jTabbedPane1.remove(1);
        txtCobrador.grabFocus();
        configuracionDateChoosers(new Date());
//        metodosGenerales.personalizarToolTips(Color.WHITE, Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        txtCobrador = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        etiquetaDeCobrador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtConf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCompania = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCuotas = new javax.swing.JTextField();
        comboModalidad = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtAdelantos = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaCuotas = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int columnindex) {

                Component component = super.prepareRenderer(renderer, row, columnindex);
                component.setBackground(Color.white);
                component.setForeground(Color.black);

                if (row <= numeroDeUltimaSemanaQueSeCobro) {
                    //  component.setBackground(new Color(102,102,255));
                    component.setForeground(Color.BLUE);
                }

                return component;

            }
        };
        btnAdelantos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tagCobrador = new javax.swing.JLabel();
        tagZona = new javax.swing.JLabel();
        btnBuscarClientes = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtBuscadorPrestamos = new javax.swing.JTextField();
        fecha2 = new com.toedter.calendar.JDateChooser();
        fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaPrestamosEliminados = new javax.swing.JTable(){
            public String getToolTipText(MouseEvent e) {
                String tip = null;
                java.awt.Point p = e.getPoint();
                int rowIndex = rowAtPoint(p);
                int colIndex = columnAtPoint(p);
                //Prestamo pre = (Prestamo) getValueAt(rowIndex, 0);
                int realColumnIndex = convertColumnIndexToModel(colIndex);

                if (realColumnIndex == 0) { //Sport column
                    if(getValueAt(rowIndex, 0)instanceof Prestamo){
                        tip = "Eliminado Por : "+((Prestamo) getValueAt(rowIndex, 0)).getDatosDeUltimaModificacion();
                    }else{
                        tip ="Devuelve a su posicion original la columna \"id\".";
                    }

                }
                return tip;
            }
        };
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtDir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTel1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTel2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtOcup = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRec = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtBuscadorClientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCobrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCobradorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCobradorKeyTyped(evt);
            }
        });

        jLabel13.setText("Imagen");

        btnAceptar.setText("jButton2");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cobrador");

        etiquetaDeCobrador.setText("jLabel14");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaDeCobrador, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 268, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaDeCobrador))
                        .addGap(119, 119, 119)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inicio", jPanel8);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuracion De Prestamos"));

        jLabel1.setText("Configuracion");

        txtConf.setFocusable(false);

        jLabel2.setText("Compania");

        txtCompania.setFocusable(false);

        jLabel3.setText("Cuotas");

        jLabel4.setText("Modalidad");

        txtCuotas.setFocusable(false);

        comboModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanal", "Diario" }));
        comboModalidad.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 81, Short.MAX_VALUE))
                            .addComponent(comboModalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(txtCompania)
                    .addComponent(txtConf, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuotas"));

        txtAdelantos.setFocusable(false);
        txtAdelantos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdelantosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdelantosKeyTyped(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("Adelantar");

        jScrollPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablaCuotas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaCuotas.setForeground(new java.awt.Color(51, 51, 51));
        tablaCuotas.setModel(modeloCuotas);
        tablaCuotas.setFocusable(false);
        tablaCuotas.setGridColor(new java.awt.Color(255, 255, 255));
        tablaCuotas.setRowHeight(20);
        tablaCuotas.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tablaCuotas.getTableHeader().setReorderingAllowed(false);
        tablaCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCuotasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaCuotas);

        btnAdelantos.setText("Aplicar");
        btnAdelantos.setEnabled(false);
        btnAdelantos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelantosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdelantos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdelantos)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdelantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(btnAdelantos))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestamo"));

        jLabel8.setText("Codigo");

        txtCodigo.setText("Cod");

        jLabel6.setText("Nombre");

        jLabel9.setText("Apellido");

        jLabel10.setText("Cedula");

        jLabel11.setText("Fecha");

        jLabel12.setText("Monto");

        tagCobrador.setText("jLabel14");

        tagZona.setText("jLabel15");

        btnBuscarClientes.setText("Clientes");
        btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientesActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);

        txtApellido.setEditable(false);

        txtCedula.setEditable(false);

        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        fechaInicial.setDateFormatString("dd/MM/yyyy");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel7.add(btnNuevo);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel7.add(btnGuardar);

        btnEditar.setText("Eliminar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel7.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel7.add(btnCancelar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(txtApellido)
                    .addComponent(txtCedula)
                    .addComponent(txtNombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarClientes, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tagZona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(tagCobrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMonto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnBuscarClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(tagCobrador)
                .addGap(13, 13, 13)
                .addComponent(tagZona)
                .addGap(39, 39, 39)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtCodigo.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Prestamos", jPanel2);

        txtBuscadorPrestamos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorPrestamosKeyReleased(evt);
            }
        });

        fecha2.setDateFormatString("dd/MM/yyyy");

        fecha1.setDateFormatString("dd/MM/yyyy");

        jLabel18.setText("Desde");

        jLabel19.setText("Hasta");

        jButton1.setText("Actualizar");

        jLabel20.setText("Buscar");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscadorPrestamos)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscadorPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tablaPrestamosEliminados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaPrestamosEliminados.setForeground(new java.awt.Color(255, 0, 51));
        tablaPrestamosEliminados.setModel(modeloPrestamosEliminados);
        tablaPrestamosEliminados.setGridColor(new java.awt.Color(255, 255, 255));
        tablaPrestamosEliminados.setRowHeight(20);
        tablaPrestamosEliminados.setSelectionBackground(new java.awt.Color(255, 0, 51));
        tablaPrestamosEliminados.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tablaPrestamosEliminados);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );

        tablaPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaPrestamos.setForeground(new java.awt.Color(51, 51, 51));
        tablaPrestamos.setModel(modeloPrestamos);
        tablaPrestamos.setGridColor(new java.awt.Color(255, 255, 255));
        tablaPrestamos.setRowHeight(20);
        tablaPrestamos.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tablaPrestamos.setShowVerticalLines(false);
        tablaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPrestamosMouseClicked(evt);
            }
        });
        tablaPrestamos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaPrestamosKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablaPrestamos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar Prestamos", jPanel3);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDir.setFocusable(false);

        jLabel5.setText("Direccion");

        txtTel1.setFocusable(false);

        jLabel14.setText("Telefono 1");

        txtTel2.setFocusable(false);

        jLabel15.setText("Telefono 2");

        txtOcup.setFocusable(false);

        jLabel16.setText("Ocupacion");

        txtRec.setFocusable(false);

        jLabel17.setText("Recomendado");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDir)
                    .addComponent(jLabel5)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOcup)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtRec, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOcup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        txtBuscadorClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorClientesKeyReleased(evt);
            }
        });

        tablaClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaClientes.setForeground(new java.awt.Color(51, 51, 51));
        tablaClientes.setModel(modeloClientes);
        tablaClientes.setGridColor(new java.awt.Color(255, 255, 255));
        tablaClientes.setRowHeight(20);
        tablaClientes.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        tablaClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        jLabel21.setText("Buscar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscadorClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscadorClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar Clientes", jPanel10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCobradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCobradorKeyReleased
        buscarCobradorPorCodigo();
    }//GEN-LAST:event_txtCobradorKeyReleased

    private void txtCobradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCobradorKeyTyped
        metodosGenerales.limitarCaracteres(evt, txtCobrador, 3);
    }//GEN-LAST:event_txtCobradorKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        funcionalidadBotonAceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
        jTabbedPane1.add(jPanel10, "Buscar Clientes");
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnBuscarClientesActionPerformed

    private void txtBuscadorClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorClientesKeyReleased
        buscarClientesPorCriterio(txtBuscadorClientes.getText());
    }//GEN-LAST:event_txtBuscadorClientesKeyReleased

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        if (evt.getClickCount() == 2) {
            rellenarCamposClientes();
        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void tablaClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaClientesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rellenarCamposClientes();
        }
    }//GEN-LAST:event_tablaClientesKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        funcionalidadDeBotonNuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        funcionalidadDeBotonCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        funcioalidadBotonEliminar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        funcionalidadDeBotonGuardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
        if (!txtMonto.getText().isEmpty()) {
            NumberFormat format = NumberFormat.getCurrencyInstance(Locale.CANADA);
            txtMonto.setText(format.format(Double.parseDouble(txtMonto.getText())));
            format = null;
        }
    }//GEN-LAST:event_txtMontoFocusLost

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        metodosGenerales.formatoNumericoTextField(evt, txtMonto, 7);
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusGained
        if (!txtMonto.getText().isEmpty()) {
//            txtMonto.setText("" + (int) Double.parseDouble(metodosGenerales.quitarFormatoDeMoneda(txtMonto.getText())));
        }
    }//GEN-LAST:event_txtMontoFocusGained

    private void txtBuscadorPrestamosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorPrestamosKeyReleased
        buscarPrestamosPorCriterio(txtBuscadorPrestamos.getText(), cobradorSeleccionado.getIdCobrador(), fecha1.getDate(), fecha2.getDate());
    }//GEN-LAST:event_txtBuscadorPrestamosKeyReleased

    private void tablaPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPrestamosMouseClicked
        if (evt.getClickCount() == 2) {
            rellenarCamposPrestamos();
        }
    }//GEN-LAST:event_tablaPrestamosMouseClicked

    private void tablaPrestamosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaPrestamosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rellenarCamposPrestamos();
        }
    }//GEN-LAST:event_tablaPrestamosKeyPressed

    private void tablaCuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCuotasMouseClicked
        Point p = evt.getPoint();
        int fila = tablaCuotas.rowAtPoint(p);
        int columna = tablaCuotas.columnAtPoint(p);

        System.out.println("Fila " + fila + " Columna " + columna);
    }//GEN-LAST:event_tablaCuotasMouseClicked

    private void btnAdelantosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelantosActionPerformed
        aplicarAdelantos();
    }//GEN-LAST:event_btnAdelantosActionPerformed

    private void txtAdelantosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdelantosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            seleccionarLosAdelantosConTxt(txtAdelantos);
        }
    }//GEN-LAST:event_txtAdelantosKeyPressed

    private void txtAdelantosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdelantosKeyTyped
        metodosGenerales.formatoNumericoTextField(evt, txtAdelantos,4);
    }//GEN-LAST:event_txtAdelantosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModuloPrestamos dialog = new ModuloPrestamos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAdelantos;
    private javax.swing.JButton btnBuscarClientes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> comboModalidad;
    private javax.swing.JLabel etiquetaDeCobrador;
    private com.toedter.calendar.JDateChooser fecha1;
    private com.toedter.calendar.JDateChooser fecha2;
    private com.toedter.calendar.JDateChooser fechaInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaCuotas;
    private javax.swing.JTable tablaPrestamos;
    private javax.swing.JTable tablaPrestamosEliminados;
    private javax.swing.JLabel tagCobrador;
    private javax.swing.JLabel tagZona;
    private javax.swing.JTextField txtAdelantos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscadorClientes;
    private javax.swing.JTextField txtBuscadorPrestamos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCobrador;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCompania;
    private javax.swing.JTextField txtConf;
    private javax.swing.JTextField txtCuotas;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOcup;
    private javax.swing.JTextField txtRec;
    private javax.swing.JTextField txtTel1;
    private javax.swing.JTextField txtTel2;
    // End of variables declaration//GEN-END:variables

    private List<JTextField> ListaDeTxt() {
        return Arrays.asList(new JTextField[]{txtNombre, txtApellido, txtCedula, txtMonto});
    }

    private void habilitarCampos(boolean valor) {
        btnBuscarClientes.setEnabled(valor);
        txtMonto.setFocusable(valor);
        btnGuardar.setEnabled(valor);
        btnEditar.setEnabled(!valor);
        txtAdelantos.setFocusable(!valor);
        btnAdelantos.setEnabled(!valor);
    }

    private void formatoTabla() {
        tablaClientes.setDefaultEditor(Object.class, null);
        String[] titulos = {"Id", "Nombre", "Apellido", "Cedula"};
        int[] tamanos = {25, 100, 200, 100};
        metodosGenerales.FormatoTablas(tablaClientes, modeloClientes, titulos, tamanos);

        tablaPrestamos.setDefaultEditor(Object.class, null);
        String[] titulos2 = {"Id", "Id Cliente", "Fecha inicio", "Nombre", "Apellido", "Monto"};
        int[] tamanos2 = {100, 100, 100, 100, 100, 100};
        metodosGenerales.FormatoTablas(tablaPrestamos, modeloPrestamos, titulos2, tamanos2);

        tablaCuotas.setDefaultEditor(Object.class, null);
        String[] titulos3 = {"Fecha", "#", "Cuota", "Ad"};
        int[] tamanos3 = {150, 50, 75, 25};
        metodosGenerales.FormatoTablas(tablaCuotas, modeloCuotas, titulos3, tamanos3);
//        metodosGenerales.anadirCheckBoxATabla(3, tablaCuotas);

        tablaPrestamosEliminados.setDefaultEditor(Object.class, null);
        metodosGenerales.FormatoTablas(tablaPrestamosEliminados, modeloPrestamosEliminados, titulos2, tamanos2);

        titulos = null;
        tamanos = null;
        titulos2 = null;
        tamanos2 = null;
        titulos3 = null;
        tamanos3 = null;
    }

    private void funcionalidadDeBotonNuevo() {
        metodosGenerales.borrarTxt(lista);
        txtAdelantos.setText("");
        metodosGenerales.LimpiarTabla(modeloCuotas);
        fechaInicial.setDate(new Date());
        habilitarCampos(true);
        btnBuscarClientes.grabFocus();
    }

    private void funcionalidadDeBotonGuardar() {

        boolean hayCampoVacio = metodosGenerales.hayUnCampoVacio(lista);

        if (!hayCampoVacio) {

            int tipoDePrestamo = comboModalidad.getSelectedIndex(); // 0 = semanal , 1 = diario;
            double monto =0;
            int idCobrador = cobradorSeleccionado.getIdCobrador();
            int idUsuario = ModuloPrincipal.usuario.getIdUsuario();
            int numeroDeCuotas = Integer.parseInt(txtCuotas.getText());
            int porciento = conf.getPorCientoBeneficio();

            Bd.insertarPrestamos(new Prestamo(
                    1, fechaInicial.getDate(), null,
                    "A", monto, idCobrador,
                    clienteSeleccionado, idUsuario, null),
                    numeroDeCuotas, porciento,
                    tipoDePrestamo);

            metodosGenerales.borrarTxt(lista);
            fechaInicial.setDate(new Date());
            btnEditar.setEnabled(false);
        }

        if (habilitarListenerDeFocus == true) {
            metodosGenerales.focusPerdidoTxt(lista);
            habilitarListenerDeFocus = false;
        }

    }

    private void funcioalidadBotonEliminar() {
        int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar este prestamo?", "Alerta", JOptionPane.YES_NO_OPTION);
        if (opcion == 0) {
            int idPrestamo = Integer.parseInt(txtCodigo.getText());
            int idUsuario = ModuloPrincipal.usuario.getIdUsuario();
            Bd.eliminarPrestamos(idPrestamo, idUsuario);
            funcionalidadDeBotonNuevo();//para que escribir todo de nuevo si ya hay una funcionalidad para esto
        }
    }

    private void funcionalidadDeBotonCancelar() {
        if (metodosGenerales.hayAlmenosUnCampoLleno(lista)) {
            // estoy pensando en cambiar esto por la funcionalidadDeNuevo al final es lo mismo.
            metodosGenerales.borrarTxt(lista);
            txtAdelantos.setText("");
            metodosGenerales.LimpiarTabla(modeloCuotas);
            fechaInicial.setDate(new Date());
            habilitarCampos(true);
        } else {
            dispose();
        }
    }

    private void funcionalidadBotonAceptar() {
        conf = ModuloPrincipal.conf;//inicializo esto aqui para no hacer carga al constructor de inicio

        if (cobradorSeleccionado != null) {

            jTabbedPane1.add(jPanel2, "Prestamos");
            jTabbedPane1.add(jPanel3, "Buscar Prestamos");
            jTabbedPane1.remove(0);

            tagCobrador.setText("COBRADOR : " + cobradorSeleccionado.getNombre());
            tagZona.setText("ZONA          : " + cobradorSeleccionado.getZona().getNombre());

            txtConf.setText(conf.getNombreConfiguracion());
            txtCompania.setText(conf.getNombreCompania());
            txtCuotas.setText("" + conf.getNumeroDeCuotas());
            comboModalidad.setSelectedItem(conf.getModalida());

        }
    }

    private void buscarCobradorPorCodigo() {
        String criterio = txtCobrador.getText();
        int configuracion = ModuloPrincipal.conf.getIdConf();
        int tamanoDeCriterio = criterio.length();

        switch (tamanoDeCriterio) {

            case 3:

                List<Cobrador> lista = Bd.buscarCobradorDeTuConfiguracion(criterio, configuracion);
                if (!lista.isEmpty()) {
                    cobradorSeleccionado = lista.get(0);
                    etiquetaDeCobrador.setText(cobradorSeleccionado.getNombre());
                    btnAceptar.grabFocus();
                } else {
                    etiquetaDeCobrador.setText("No existe.");
                }
                lista = null;

                break;

            default:
                etiquetaDeCobrador.setText("");
                break;
        }
    }

    private void buscarClientesPorCriterio(String criterio) {
        metodosGenerales.LimpiarTabla(modeloClientes);
        List<Cliente> lista = Bd.buscarClienteDependiendoLaZona(criterio, cobradorSeleccionado.getZona().getIdZona());
        modeloClientes.setRowCount(lista.size());
        Cliente c;

        for (int i = 0; i < lista.size(); i++) {
            c = lista.get(i);
            modeloClientes.setValueAt(c.getIdCliente(), i, 0);
            modeloClientes.setValueAt(c, i, 1);
            modeloClientes.setValueAt(c.getApellido(), i, 2);
            modeloClientes.setValueAt(c.getCedula(), i, 3);

        }
        lista = null;
        c = null;
    }

    private void buscarPrestamosPorCriterio(String criterio, int idCobrador, Date fecha1, Date fecha2) {

        if (fecha1 != null && fecha2 != null) {

            metodosGenerales.LimpiarTabla(modeloPrestamos);
            metodosGenerales.LimpiarTabla(modeloPrestamosEliminados);

            List<Prestamo> lista = Bd.buscarPrestamoPorCriterio(criterio, idCobrador, fecha1.getTime(), fecha2.getTime(),"");
            List<Prestamo> listaPrestamosActivos = lista.stream().filter(pr -> pr.getEstado().equals("A")).collect(Collectors.toList());
            List<Prestamo> listaPrestamosEliminados = lista.stream().filter(pr -> pr.getEstado().equals("E")).collect(Collectors.toList());

            modeloPrestamos.setRowCount(listaPrestamosActivos.size());
            modeloPrestamosEliminados.setRowCount(listaPrestamosEliminados.size());

            Prestamo p;

            for (int i = 0; i < listaPrestamosActivos.size(); i++) {
                p = listaPrestamosActivos.get(i);
                modeloPrestamos.setValueAt(p, i, 0);
                modeloPrestamos.setValueAt(p.getCliente().getIdCliente(), i, 1);
                modeloPrestamos.setValueAt(p.getFechaInicialFormateada(), i, 2);
                modeloPrestamos.setValueAt(p.getCliente(), i, 3);
                modeloPrestamos.setValueAt(p.getCliente().getApellido(), i, 4);
                modeloPrestamos.setValueAt(p.getMontoFormateado(), i, 5);
            }

            for (int i = 0; i < listaPrestamosEliminados.size(); i++) {
                p = listaPrestamosEliminados.get(i);
                modeloPrestamosEliminados.setValueAt(p, i, 0);
                modeloPrestamosEliminados.setValueAt(p.getCliente().getIdCliente(), i, 1);
                modeloPrestamosEliminados.setValueAt(p.getFechaInicialFormateada(), i, 2);
                modeloPrestamosEliminados.setValueAt(p.getCliente(), i, 3);
                modeloPrestamosEliminados.setValueAt(p.getCliente().getApellido(), i, 4);
                modeloPrestamosEliminados.setValueAt(p.getMontoFormateado(), i, 5);
            }

            lista = null;
            listaPrestamosActivos = null;
            listaPrestamosEliminados = null;
            p = null;

        } else {
            System.out.println("Fecha Invalida");
        }

    }

    public void rellenarCamposClientes() {

        int filaSeleccionada = tablaClientes.getSelectedRow();
        clienteSeleccionado = (Cliente) tablaClientes.getValueAt(filaSeleccionada, 1);

        txtNombre.setText(clienteSeleccionado.getNombre());
        txtApellido.setText(clienteSeleccionado.getApellido());
        txtCedula.setText(clienteSeleccionado.getCedula());
        txtMonto.setText("");

        metodosGenerales.LimpiarTabla(modeloClientes);//anadido despues
        metodosGenerales.borrarTxt(Arrays.asList(new JTextField[]{txtDir, txtTel1, txtTel2, txtOcup, txtRec}));//solo quiero eliminar esos , no todos.
        //esto no funciona hasta ahora.                                            //actualizacion esto borra los campo de la barrita de info del cliente.
        txtMonto.grabFocus();
        jTabbedPane1.setSelectedIndex(0);
    }

    public void rellenarCamposPrestamos() {
        int filaSeleccionada = tablaPrestamos.getSelectedRow();
        clienteSeleccionado = (Cliente) tablaPrestamos.getValueAt(filaSeleccionada, 3);
        Prestamo p = (Prestamo) tablaPrestamos.getValueAt(filaSeleccionada, 0);

        txtCodigo.setText("" + p.getIdPrestamo());
        txtNombre.setText(clienteSeleccionado.getNombre());
        txtApellido.setText(clienteSeleccionado.getApellido());
        txtCedula.setText(clienteSeleccionado.getCedula());
        txtMonto.setText(p.getMontoFormateado());
        fechaInicial.setDate(p.getFechaInicial());

        GenerarCuotasParaLaTablita(p);

        metodosGenerales.LimpiarTabla(modeloPrestamos);//anadido despues
        metodosGenerales.LimpiarTabla(modeloPrestamosEliminados);
        habilitarCampos(false);

        if (jTabbedPane1.getTabCount() > 2) {
            jTabbedPane1.remove(2);
        }
        jTabbedPane1.setSelectedIndex(0);

        p = null;

    }

    private void eventoAlSeleccionarUnEmpleado() {
        tablaClientes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && tablaClientes.getSelectedRow() >= 0) {
                    int filaSeleccionada = tablaClientes.getSelectedRow();
                    clienteSeleccionado = (Cliente) tablaClientes.getValueAt(filaSeleccionada, 1);
                    txtDir.setText(clienteSeleccionado.getDireccion());
                    txtTel1.setText(clienteSeleccionado.getTelefono1());
                    txtTel2.setText(clienteSeleccionado.getTelefono2());
                    txtOcup.setText(clienteSeleccionado.getOcupacion());
                    txtRec.setText(clienteSeleccionado.getRecomendado());
                }
            }
        });
    }

    public void GenerarCuotasParaLaTablita(Prestamo prestamo) {
        List<Recibo> listaRecibos = Bd.buscarRecibos(prestamo.getIdPrestamo());
        int tamanoDeLista = listaRecibos.size();
        modeloCuotas.setRowCount(tamanoDeLista);
        int resultado = -2;

        for (int i = 0; i < tamanoDeLista; i++) {
            Recibo r = listaRecibos.get(i);
            tablaCuotas.setValueAt(r.getFechaFormateada(), i, 0);
            tablaCuotas.setValueAt(r, i, 1);
            tablaCuotas.setValueAt(r.getCuotaFormateada(), i, 2);
            tablaCuotas.setValueAt(r.estaEnAdelanto(), i, 3);
        }
        //esta parte de codigo abajo sirve para generar el index dicha variable se utilizs
        //en un porcion de codigo dentro de la tabla de cuotas.

        for (int i = 0; i < tamanoDeLista; i++) {
            Recibo r = listaRecibos.get(i);
            //resultado = r.getFecha().compareTo(metodosGenerales.fechaSinHora(new Date()));

            switch (resultado) {
                case 0:
                    //System.out.println("Las Fechas Son IGUALES");
                    numeroDeUltimaSemanaQueSeCobro = i - 1;
                    return;
                case 1:
                    //System.out.println("La fecha De mi recibo es MAYOR que la actual");
                    numeroDeUltimaSemanaQueSeCobro = i - 1;
                    return;
                case -1:
                    // System.out.println("La fech de mi recibo es MENOR que la actual");
                    numeroDeUltimaSemanaQueSeCobro = i;
                    break;
            }
        }
    }

    private void configuracionDateChoosers(Date fecha) {
        fechaInicial.setDate(fecha);
        Calendar c = Calendar.getInstance();

        c.setTime(fecha);
        c.set(Calendar.DAY_OF_MONTH, 1);

        fecha1.setDate(c.getTime());

        c.add(Calendar.MONTH, 1);

        fecha2.setDate(c.getTime());

       //JTextFieldDateEditor f = (JTextFieldDateEditor) fechaInicial.getDateEditor();
       //f.setFocusable(false);
       //fechaInicial.getCalendarButton().setEnabled(false);
       fechaInicial.getJCalendar().setPreferredSize(new Dimension(600, 500));
       fechaInicial.getJCalendar().getMonthChooser().setSize(100,100);
    }

    private void seleccionarLosAdelantosConTxt(JTextField txt) {
        
        int hastaQueCuota = Integer.parseInt(txt.getText());
        int numeroDeCuotas = tablaCuotas.getRowCount();
        

        if (hastaQueCuota <= numeroDeCuotas && hastaQueCuota >= 0) {

            //Pongo todos los valores falsos para luego aplicar donde quiero
            for (int i = numeroDeUltimaSemanaQueSeCobro + 1; i < numeroDeCuotas; i++) {
                tablaCuotas.setValueAt(false, i, 3);
            }

            //Pongo los valores verdaderos que quiero hasta donde quiero
            for (int i = numeroDeUltimaSemanaQueSeCobro + 1; i < hastaQueCuota; i++) {
                tablaCuotas.setValueAt(true, i, 3);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Ehmm amigo tu numero debes estar entre 0 y " + numeroDeCuotas);
        }

    }

    private void aplicarAdelantos() {
        
        if(!txtAdelantos.getText().isEmpty()){
            seleccionarLosAdelantosConTxt(txtAdelantos);
        }
        
        int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro de aplicar este adelanto ?", "Aviso", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) {
            
            List indicesQueSeModificaran = new ArrayList();
            List numeroDeCuotasQueEstaranEnAdelantos = new ArrayList();
            int numeroDeCuotas = tablaCuotas.getRowCount();
            int indiceDePrestamo = ((Recibo) tablaCuotas.getValueAt(0, 1)).getIdPrestamo();

            for (int i = 0; i < numeroDeCuotas; i++) {
                
                if (((boolean) tablaCuotas.getValueAt(i, 3)) == true) {
                    
                    indicesQueSeModificaran.add(((Recibo) tablaCuotas.getValueAt(i, 1)).getIdRecibo());
                    numeroDeCuotasQueEstaranEnAdelantos.add(((Recibo) tablaCuotas.getValueAt(i, 1)).getNumeroCuota());
                    
                }
                
            }

            System.out.println("Indices que se modificaran " + indicesQueSeModificaran);

            Bd.ponerRecibosEnAdelantos(indiceDePrestamo, indicesQueSeModificaran);
            JOptionPane.showMessageDialog(this, "Estos recibos estaran en adelantos : \n " + numeroDeCuotasQueEstaranEnAdelantos);
            funcionalidadDeBotonNuevo();
        }
    }

}
